load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "provider",
    srcs = [
        "custom_event_source_resource.go",
        "environment_data.go",
        "environment_resource.go",
        "escalation_policy_data.go",
        "escalation_policy_resource.go",
        "functionality_data.go",
        "functionality_resource.go",
        "inbound_email_resource.go",
        "incident_role_data.go",
        "incident_role_resource.go",
        "incident_type_data.go",
        "incident_type_resource.go",
        "ingest_url_data.go",
        "lifecycle_milestone_resource.go",
        "lifecycle_phase_data.go",
        "on_call_schedule_data.go",
        "on_call_schedule_resource.go",
        "on_call_schedules_data.go",
        "permissions_data.go",
        "priority_data.go",
        "priority_resource.go",
        "provider.go",
        "role_data.go",
        "role_resource.go",
        "rotation_data.go",
        "rotation_resource.go",
        "runbook_action_data.go",
        "runbook_data.go",
        "runbook_resource.go",
        "schedule_data.go",
        "sdk_helpers.go",
        "service_data.go",
        "service_dependency_resource.go",
        "service_resource.go",
        "services_data.go",
        "severity_data.go",
        "severity_resource.go",
        "signal_rule_data.go",
        "signal_rule_resource.go",
        "slack_channel_data.go",
        "status_update_template_resource.go",
        "task_list_data.go",
        "task_list_resource.go",
        "team_data.go",
        "team_resource.go",
        "teams_data.go",
        "test_helpers.go",
        "test_resources.go",
        "user_data.go",
    ],
    importpath = "github.com/firehydrant/terraform-provider-firehydrant/provider",
    visibility = ["//visibility:public"],
    deps = [
        "//firehydrant",
        "@com_github_davecgh_go_spew//spew",
        "@com_github_firehydrant_firehydrant_go_sdk//models/components",
        "@com_github_firehydrant_firehydrant_go_sdk//models/operations",
        "@com_github_firehydrant_firehydrant_go_sdk//models/sdkerrors",
        "@com_github_hashicorp_go_cty//cty",
        "@com_github_hashicorp_terraform_plugin_log//tflog",
        "@com_github_hashicorp_terraform_plugin_sdk_v2//diag",
        "@com_github_hashicorp_terraform_plugin_sdk_v2//helper/resource",
        "@com_github_hashicorp_terraform_plugin_sdk_v2//helper/schema",
        "@com_github_hashicorp_terraform_plugin_sdk_v2//helper/structure",
        "@com_github_hashicorp_terraform_plugin_sdk_v2//helper/validation",
        "@com_github_hashicorp_terraform_plugin_sdk_v2//terraform",
        "@com_github_senseyeio_duration//:duration",
    ],
)

go_test(
    name = "provider_test",
    srcs = [
        "custom_event_source_resource_test.go",
        "environment_data_test.go",
        "environment_resource_test.go",
        "escalation_policy_data_test.go",
        "escalation_policy_resource_test.go",
        "functionality_data_test.go",
        "functionality_resource_test.go",
        "inbound_email_resource_test.go",
        "incident_role_data_test.go",
        "incident_role_resource_test.go",
        "incident_type_data_test.go",
        "incident_type_resource_test.go",
        "ingest_url_data_test.go",
        "lifecycle_milestone_resource_test.go",
        "lifecycle_phase_data_test.go",
        "on_call_schedule_data_test.go",
        "on_call_schedule_resource_test.go",
        "on_call_schedules_data_test.go",
        "permissions_data_test.go",
        "priority_data_test.go",
        "priority_resource_test.go",
        "provider_test.go",
        "role_data_test.go",
        "role_resource_test.go",
        "rotation_data_test.go",
        "rotation_resource_test.go",
        "runbook_action_data_test.go",
        "runbook_data_test.go",
        "runbook_resource_test.go",
        "schedule_data_test.go",
        "sdk_helpers_test.go",
        "service_data_test.go",
        "service_dependency_resource_test.go",
        "service_resource_test.go",
        "services_data_test.go",
        "severity_data_test.go",
        "severity_resource_test.go",
        "signal_rule_data_test.go",
        "signal_rule_resource_test.go",
        "slack_channel_data_test.go",
        "status_update_template_resource_test.go",
        "task_list_data_test.go",
        "task_list_resource_test.go",
        "team_data_test.go",
        "team_resource_test.go",
        "teams_data_test.go",
        "user_data_test.go",
    ],
    embed = [":provider"],
    deps = [
        "//firehydrant",
        "@com_github_firehydrant_firehydrant_go_sdk//:firehydrant-go-sdk",
        "@com_github_firehydrant_firehydrant_go_sdk//models/components",
        "@com_github_hashicorp_terraform_plugin_sdk_v2//helper/acctest",
        "@com_github_hashicorp_terraform_plugin_sdk_v2//helper/resource",
        "@com_github_hashicorp_terraform_plugin_sdk_v2//helper/schema",
        "@com_github_hashicorp_terraform_plugin_sdk_v2//helper/structure",
        "@com_github_hashicorp_terraform_plugin_sdk_v2//terraform",
        "@com_github_stretchr_testify//suite",
    ],
)
